services:
  - type: web
    name: decant-lab
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MP_PUBLIC_KEY
        sync: false
      - key: MP_ACCESS_TOKEN
        sync: false
